# Site settings
title:       Captains-log
author:      Masha Safina
description: ":rocket: This is my personal blog, deal with it"
baseurl:     "/blog" 
url:         "http://mashlo.github.io" 

# Social Links
email:            safe@masha.space
twitter_username: mashasafina
github_username:  mashlo

# Build settings
markdown: kramdown
permalink: pretty
